import re
from string import punctuation
from nltk.corpus import stopwords
from nltk.tokenize import TweetTokenizer

punctuation += '΄´’…“”–—―»«' # string.punctuation misses these.

cache_english_stopwords = stopwords.words('english')

def tweet_clean(tweet):
    #print('Original tweet:', tweet, '\n')
    # Remove HTML special entities (e.g. &amp;)
    tweet_no_special_entities = re.sub(r'\&\w*;', '', tweet)
    #print('No special entitites:', tweet_no_special_entities, '\n')
    # Remove tickers
    tweet_no_tickers = re.sub(r'\$\w*', '', tweet_no_special_entities)
    #print('No tickers:', tweet_no_tickers, '\n')
    # Remove hyperlinks
    tweet_no_hyperlinks = re.sub(r'https?:\/\/.*\/\w*', '', tweet_no_tickers)
    #print('No hyperlinks:', tweet_no_hyperlinks, '\n')
    # Remove hashtags
    tweet_no_hashtags = re.sub(r'#\w*', '', tweet_no_hyperlinks)
    #print('No hashtags:', tweet_no_hashtags, '\n')
    # Remove Punctuation and split 's, 't, 've with a space for filter
    tweet_no_punctuation = re.sub(r'[' + punctuation.replace('@', '') + ']+', ' ', tweet_no_hashtags)
    #print('No punctuation:', tweet_no_punctuation, '\n')
    # Remove words with 2 or fewer letters
    tweet_no_small_words = re.sub(r'\b\w{1,2}\b', '', tweet_no_punctuation)
    #print('No small words:', tweet_no_small_words, '\n')
    # Remove whitespace (including new line characters)
    tweet_no_whitespace = re.sub(r'\s\s+', ' ', tweet_no_small_words) 
    tweet_no_whitespace = tweet_no_whitespace.lstrip(' ') # Remove single space remaining at the front of the tweet.
    #print('No whitespace:', tweet_no_whitespace, '\n')
	# Remove characters beyond Basic Multilingual Plane (BMP) of Unicode:
    tweet_no_emojis = ''.join(c for c in tweet_no_whitespace if c <= '\uFFFF') # Apart from emojis (plane 1), this also removes historic scripts and mathematical alphanumerics (also plane 1), ideographs (plane 2) and more.
    #print('No emojis:', tweet_no_emojis, '\n')
    # Tokenize: Change to lowercase, reduce length and remove handles
    tknzr = TweetTokenizer(preserve_case=False, reduce_len=True, strip_handles=True) # reduce_len changes, for example, waaaaaayyyy to waaayyy.
    tw_list = tknzr.tokenize(tweet_no_emojis)
    #print('Tweet tokenize:', tw_list, '\n')
    # Remove stopwords
    #list_no_stopwords = [i for i in tw_list if i not in cache_english_stopwords]
    #print('No stop words:', list_no_stopwords, '\n')
    # Final filtered tweet
    tweet_filtered =' '.join(tw_list)
    print(re.sub(r'[^a-zA-Z0-9]',' ',tweet_filtered))

s = ['prayers are not helping the nepal earthquake victims donation volunteers deployment rescuers professional the ground wht they need',
'shelter fuel food medicine power news workers nepal earthquake hit capital was short everyth',
'high possibility air and water borne diseases people are open spaces with nutritious food and saf',
'request spgc pls send food needy people nepal they want food and water pls send them soon possible',
'ppl nepal need food medicines biblehow inhumane shameless creature',
'nearly million children require urgent humanitarian assistance after nepal earthquake',
'houses damaged commodities supply low 000 tents need patients',
'calling community urge their families donate blood type mostly needed',
'sounds traffic are back this morning kathmandu people are still displaced electricity running water',
'pls send medicines and food nepal you plz contact for better coordination',
'after observation humbly request with nepal government that please provide drinkable water every small big safety cam',
'dear rescue team have run out supplies including water food tents this location            ',
'colleagues nepal acute need for orthopaedic surgeons and cardiothoracic surgeons trauma specialists  ',
'operation maitri can give birth already dead 2000 nepal will needing medical aid injured',
'least people should get drink not food immediately',
'this how people trying keep themselves warm tonite needs warm cloths food',
'minister rijal said 000 tents needed house patients forced out damaged hospital wards',
'sir plz 4ward this tweet rqt all helpful ppl donate bloods nearby hospitals blood scarce nepal hospitals',
'need provide more tents',
'india could surely despatch field ambulance units nepal they need now',
'requirement ambulances and buses requested rescue ppl nepal hope you have decided',
'gunarathna jacqueline fans nepal pple desperate food medicine shelter frm least 900 people dead',
'doctors say there enough manpower but less beds opds and medicines the hospital',
'people there need food shelter not gospel lord pashupatinath there take care nepal',
'need medium heavy lift hepters fixed wing aircraft water treatment plants urgently ram sharan mahant fin min',
'big numbers people are waiting for flight nepal they dont have food frm yesterday even not have water painful',
'lac rail neer bottles not what nepal needs needs crore liters drinking water',
'need more resources and personnel from army for restoring power bridges roads and have substantial presence nepal',
'appeal every one donate blood for the injured earthquake india nepal',
'earthquake huge requirement food water smaller villages outside the cities tag ngos individuals',
'isn begging for food water today they are begging for body bags can even imagine how horrific',
'people nepal waiting for more help please send more help the earliest they need blood medicean water and food packet',
'per bbc report over 500 people died nepal earthquake some areas received water food help even thirdday',
'plz send medicine and food packets nepal possible',
'plunges despair kathmandu classic case urban disaster temporary shelter big need',
'our thoughts are with the people large need for surgical care even before the earthquake http',
'nepal urgently needs tent food medicine doctors hrs past still thinking about india sent tones relief with hours',
'give protection for nepal give for food water and medician india help for nepal',
'nepal urges people donate blood',
'3novices after losing homes people earthquake hit nepal face food crisis with aftershocks spreading fear and thousands pitching tents',
'pls send buses evaquate people arrande droping water food blanket nepal save life',
'blood donations needed call manita 98510 84500 nepal red cross blood bank',
'please help get some tent tarpaulin patients need none want indoors help pls',
'million need humantarian assistance',
'glad hear from more friends internet back but great shortage and they say',
'nytimes nytimesworld earthquake victims sleeping outside nepal water and food are scarce live update',
'please donate meat free food quake affected people',
'about houses damaged essential commodities supply running low 000 tents need house patients dam',
'powerful earthquake has hit nepal oxfam there urgently need your help provide clean water sanitation https',
'our brethren nepal need massive humanitarian need all schools colleges and universities must conduct blood donation camps priority',
'donate blood and save lifes are with',
'nepal urgent messages for expertise disaster management including cardiothoracic surgery collapse command',
'nepal doesn need money but needs special forces with equipment water tents medicines directly victims',
'earthquake survivors urgently need help give lifesaving food today and help respond',
'soul plz provide medicine blood food clean water shelter and moral support people',
'sir nepal need more medical kind help have response cure our brothers and sisters and our families',
'immediate health needs acc who medical tent bed capacity 100surgical kits iehk kitsbody',
'collecting funds for nepal earthquake victims generous pls donate blood medicines mineral water blankets and',
'donate money help survivors nepal get food water and shelter not churches',
'you can donate water old cloths medicines bandages anything helpful for the earthquake victims location',
'earthquake survivors urgently need help give lifesaving food today and help respond',
'people desperate for food medicine shelter from least 900 people are dead',
'electricity shelter communication food',
'lack blood blood bank nepal  bbcworld  ibnlive',
'teaching hospital injured are getting treatment open space tents are urgent need',
'nepal earthquake thousands need shelter country little able cope',
'thousand indians stranded nepal plz help them water nothing eat queuing outside airport',
'people are running out water foods please help',
'very much shortage food packet nepal per timesnow news report hope already started serve the people',
'victims require neuros anaesthetists paramedics plz volunteer',
'there shortage blood well oxygen cylinders nepal huge crisis',
'nepal govt has asked india for help with respect rescue medical teams',
'you should visit nepal they need medical store',
'immense shortage drinking water why hasn and stepped yet',
'can keep announicing for nepal while people die relief supplies medicine doctors needed not dollars',
'modi can you send some doctor for nepal nepal people needd',
'help provide food shelter medicines quate victims nepal nepalquakehelp',
'nepal needs help needs food medicine relief materials for people distress doesn need ramdev nuisance value',
'kathmandu hospitals struggling after nepal earthquake generous blood donors needed asap http',
'need medium heavy lift helicopters fixed wing aircraft water treatment plants urgently ram sharan mahant finmin nepal',
'clean water food rescue medicos need the nation now',
'body bags tents water medicine pain killers urgently needed stricken',
'need your help support contribution for victim pls help the way you can',
'requested modi please provide some dry food biscuits mineral waters for nepal effected people',
'earthquake nepal has exposed its medical facilities hospitals struggle treat vast numbers injured with limited supplies and staff',
'earthquake victims hospital please help with foods cloths shelther food bed blankets etc',
'for rescue and relief during earthquake following types people needed skilled rescuer doctors',
'friend from nepal msgd that huge scarcity tents food lot more needed done grnd nepal',
'earthquake survivors urgently need help give lifesaving food today and help respond',
'rightwingers all religions must keep away from nepal the survivors not need your bullshit they need food water med',
'food first aid tents would the principal needs those displaced the earthquake',
'send some food water nepal',
'sir incidents like earthquake there need for more orthopedicians appeal statescentre send ortho team nepal',
'now can see many people lying bicc ground many them without tent cold wind searching for foods tent',
'please provide medicine and aid nepal',
'after losing homes people earthquake hit nepal face food crisis with aftershocks spreading fear and thous http',
'tents plastic sheets blankets must required nepal all can contribute hopefully channels will give address organizations',
'lots people will needing water and food aid please kick few bucks for instance via oxfam',
'click here support earthquake nepal food drinking water tent',
'nepal medical college jorpati tent tarpaulin needed urgent where got redcross facilitate',
'walked all arnd central old ktm shops out bottled water recharge cards dry food stock low grid off many parts',
'can please ask blood banks across india pitch with the blood bottles for nepal',
'can anyone know pick the 2000 second hand tents from sunauli and distribute the people need nepal',
'can keep announicing for nepal while people die relief supplies medicine doctors needed not dollars insensitivity precictble 2',
  'floret kathmandu alone not they need help outside valley aswell whr people facilities like internet etc',
  'physio dont need money all need food water medicine help people nepal instead donating money help them send',
'surgical needs are important the event earthquake like',
'aftershocks rain lack shelter and fears nepal that water and power will run out',
'tht hospitals may face shortage oxygen   medicine',
'world community needs humanitarian aid rescue medical aid',
'teams start focusing from rescue relief after earthquake shortage food fuel medicines wate',
'unicef delivering prepositioned supplies meet children immediate needs for protection water sanitation',
'our farmers need just compensation but survivors earthquake needs food water shelter medicines compensations and capital',
'urgent blood shortage for blood donation call manita 98510 84500 nepal red cross',
'nepal requests citizens donate blood outlook wires',
'victims sleeping outside nepal water and food are scarce',
'earthquake huge requirement food water smaller villages outside the cities tag ngos individuals',
'almost one million children urgent need aid after nepal earthquake',
'blood donations apparently shortage certain types please call manita 98510 84500 nepal red cross blood via kank mani dixit',
'from water electricity safe shelter toilets food and rain you facing lot citizens have strength and safe',
'need blood nepal red cross society has announce that are loosing the blood from blood bank htt',
'nepal hospitals are running out drugs and the rescue efforts need support just donated the red cross appeal',
'pls donate blood blood banks and hospitals',
'sushil koirala requests for urgent blood donation for victims rescued from htt',
'earthquake nepal rescue team has seen ppl the epicenter monsoons dieing food shelter water laprak flattened',
'india sends mobile hospital with doctors medical aid hospitals nepal don have enough rooms doctors help',
'hope for rain nepal quake victims sleeping outside water food scarce',
'due heavy damage houses nepal needs tents first aid medicine food supplies',
'donate blood help nepalblood donation going nivedita multispeciality hospital pradhan nagar',
'contribute food water medicines shelters sanitation and basic relief materials needed for',
'need provide clean water urgently roger hodgson save the children nepal',
'area need mask',
'rescue team needed gorkha gandaki western region nepal',
'teaching hospital kathmandu medical hospital and many others urgently need blood plz donate',
'people kathmandu are out the cold streets without food water electricity connectivity',
'bista rural regions nepal outside kathmandu still need emergency help sanga homes have been decimated',
'doing great job sending medical staffs nepal doctors are badly needed there good samritan',
'nepal earthquake thousands need shelter country little able cope',
'deupur gairibisauna kavre houses left food and livestock trapped under debris plz for help anyone',
'shristi thousands people are waiting for food drinking water open space after earthquake plz help them',
'nepalis water electricity water essential supplied the affected people nepal',
'distribution tents water and food too haphazard people complain access these relief items',
'people need blood can india help them providing the some blood',
'need your donation get immediate food assistance victims the',
'rainfall start bhaktapur nepal create another problem for the people camps sanitation and clean drinking water needed',
'styles thank you for tweeting this please donate food money blankets water nepal need you today prayfornepal',
'newsi requested all news channels please provide some dry food biscuits mineral waters for nepal effected people',
'watch rescue team needed gorkha gandaki western region nepal',
'urgent need analgesic antibiotics betadiene swabs kathmandu call for help 9851166044  ',
'survivor being dug out rubble nepal earthquake over 1400 killed many trapped medical supplies requested',
'hospitals seem filling fast need mobile makeshift india http',
'please help nepal help needed there thousands are dying without water foods medicines',
'nepal govt minister urgently need body bags tents and water',
'pickaxes shovels and earth moving equipment required nepal',
'jason kabre district miles outside kathmandu 100 000 homeless hospitals down last hours generator fuel',
'indians stranded nepal sundhara relief camp need help without food water please check news',
'damage houses swept away rescue team needed gorkha gandaki western region nepal',
'nepal earthquake thousands need shelter country little able cope',
'sadly not doctor nurse help out the nepal',
'what nepal will need clothes blanketsdried food biscuits etc portable toilets japan shld donate medicines water',
'great work   nepal blood bank has now announced for the need more blood please spre',
'nepal needs drinking water and fuel food hope india takes care',
'dear rescue team have run out supplies including water food tents this location            ',
'important deployment field hospital from urgent need for health care nepal lives can saved',
'its time need international agency tackle such emergency cant setup some agency the lines socie',
'crimes warrior breakingafter earthquake top requirement nepalfood water blanket medicine tentnepal embassy officials india',
'teams start focusing from rescue relief after earthquake shortage food fuel medicines wate',
'prey for nepal help nepal any form food shelter money water medicine any help you can',
'list meds needed bir hospital',
'spoke brother urgent need clearly water food and shelter rain coming down and aftershocks continuing',
'dear rescue team have run out supplies including water food tents this location            ',
'oxfam appeal launched deliver water sanitation and emergency food supplies please donate here',
'ayon mobilizing support for victims urgent need doctors food supply water purifier tent',
'nepal needs aid rebuild but first priority rescue those who are alive debris need medical treatment injured',
'they are search blood donors for the people who are injured earthquake help',
'nepal koirala requests citizens donate blood read',
'plz provide water nepal',
'tents food water sanitation medicine need the hour',
'spent three hours trama center people are coming more and more more volunteers doctor needed earth quick',
'anyone near dhadagaun near nagarkot kavre need help there few people are stuck over there with many',
'blood donations apparently shortage certain types please call manita 98510 84500 nepal red cross blood bank',
'volunteers needed',
'anybody interested donating food medicine water and sanitation materials for earthquake victims contact art http',
'nepal devastated quake help provide immediate medical care food water text mfr 41444',
'nepal earthquake survivors fight for food kathmandu via',
  'diksha after the earthquake water supply was cut off because waterworks were damaged and power plants were shut down',
'                             ',
'',
'                                                                                   ',
'                               ',
               'ntv                                                               ',
                                                     'blood                          ',
'                                                                         ',
'                           ',
'idf rescue team medical corps way nepal plus magen david odom hatzalah medics',
'nepal earthquake dsgmc sgpc send 000 food packets every day kathmandu',
'000 food packets earthquake hit nepal from the golden temple daily another reason proud being',
'indian army medical teammedical equipment being loaded onto iaf earlier today sent nepal',
'3novices israel sending aid teams nepal after quake israel was sending delegation nepal saturday determ',
'sikh bodies send food packets for nepal quake victims delhi sikh gurdwara management committee dsgmc and',
'and civil team sent for relief sunday htt',
'shiromani gurdwara parbandhak committee sgpc send food relief material nepal',
'efforts dera sacha sauda green force are truly appreciable 16000 food packages mobilized nepal',
'all gorkha regiments indianarmy send nepali gorkha jawans with medical officers assist operations',
'india ndrf teams 400 ppl nepal equipped with sniffer dogs steel concrete cutters sensors detect dead alive',
'langar meals available sikh gurdwara kupondol near bagmati bridge',
'our kit was stocked already with food water shops are open now and will picking more supplies',
'earthquake golden temple send lac and delhigurdwaras send meals daily those who love',
'pak sends planes with relief goods and several paramedics rescue workers earthquake hit pti',
'anyone trapped need rescue call 977 9851281 363 police help share many possible',
'earthquake nepal golden temple send lac and delhi gurdwaras send meals daily proud sikh',
'indian power minster has offered send engineers and equipment restore the power grids nepal',
'pakistan sends medical and food supplies nepal',
'rescue operations are on4 more flights sent nepal with ready food medicinessniffer dogs are flown',
'guruka 2000 volunteers will nepal with food medicines clothes',
'india sent team nepal for relief work which include doctor army sniffer dogs and medicine',
'sent 16000 food packets nepal the call',
'all donated blood our counters offering food water our tent toilets useful sufferers baba ramdev nepal ani http',
'delhi sikh gurdwara management committee will send 25000 food packages every day nepal',
'the union health and family welfare ministry has rushed tonnes medicines nepal today',
'airforce flight which took medics and medicine nepal fly down sri lankans tonight',
'rajnath singh instructed ssb set camps along the border provide medical help tourists crossing india nepal border',
'sikh bodies send food packets for nepal quake victims delhi sikh gurdwara management',
'israel sending aid team nepal after quake jerusalem israel was sending delegation http',
'3novices india sends rail neer water quake hit nepal the indian railways which produces its own packaged drinking water serve its',
'medical teams being deployed nepal including teams which have already reached indian army http',
'piyush goyal has offered send engineers equipment restore the power grids nepalimportant contacts http',
'patniak now govt sending 000 packets food 000 pouches drinking water nepal',
'air force plane reaches nepal with relief material medical team for victims http',
'immediately transferring 11 000 plastic sheets 4 000 solar lamps our stocks 2help',
'can make food packets and send nepal this logistics help required can govt help this',
'planes have left for nepal with food items and rescue teams are planning more',
'fyi indiasent tonnes meds member med team ortho surgeons anesthetists nurses technici',
'free medicine free delivery prasit kandel 9851133822 shailesh sharma 9851017553',
'nepal sikh bodies send food packets for nepal quake victims',
'free food and accommodation for victims gorakhnath temple adityanath',
'sikh sevak from golden temple send 100 000 food packets earthquake hit nepal',
'per the reqmnt raised pmo 16000 packed food has already been dispatched nepal',
'for food and blood teachinghospital 4412404 441250 bishal bazaar ambulance service 977 4244121',
'sgpc gurdwaras sending 25000 food packets daily nepal for earthquake victims this community always top prompt service great',
'130 air crafts with facilities bed hospital will dispatched nepal pak today good nepal need all',
'let hope least one reaches nepal news have sent trucks with mineral water cabinet min chaudhary',
'thousand water bottle has been dispatched indian railway nepal',
'pakistan sends medical search and rescue teams nepal prime minister nawaz sharif',
'sikh bodies send langar for nepal earthquake victims',
'tarp had more than ppl men rest women girls infants got food from canteen near bir hospital',
'delhi sikhgurdwaracommitteemanagement sending 25000 food pkts earthquake affectednepal earlierhelped jkpeople',
'sikh organization send lakh food packets hit nepal from the golden temple http',
'india sends rail neer water quake hit nepal the indian railways which produces its own packaged drinking',
'sikh organization send 100 000 food packets earthquake hit nepal from the golden temple',
'jpnadda bjp rushed tonnes medicines member team doctors and medical experts quake hit areas nepal',
'yoga guru baba ramdev and members his organization donating blood the needy',
'angel nepal golden temple send lakh meals delhi gurudwaras send 25k meals daily sikhism',
'indian defence forces plan ten more flights today nepal carrying army engineering and medical teams for',
'indian offers units tents units family packs etc earthquake victims nepal picture still',
'doing great job sending medical staffs nepal doctors are badly needed there good samritan',
'delhi government send food packets drinking water nepal via',
'delhi govt send food packets drinking water nepal zee news delhi govt send food',
'will send trucks water trucks biscuit and truck life saving medicines nepal',
'israel preparing emergency aid send help victims the earthquake',
'jpn the food packets would sent nepal with help indian air force',
'israeli mfa director general israel will send humanitarian aid nepal and will establish field hospital katmandu',
'ndrf teams have been sent bihar and ndrf team operation rajnath singh',
'nepal earthquake china sends search and rescue teams with six sniffer dogs and relevant rescue and medical',
'bishal bazaar ambulance service 977 4244121 please',
'1000s nepali gorkhas serving indian army sent nepal army doctors aid ops gr8 idea',
'cont nepal indian railway and railway minister have sent 1000 water bottles nepal hats off all',
'earthquake nepal golden temple send 1lac and delhi gurdwaras send 25k meals daily those who share',
'darbhanga medical collage hospital assured best help earthquake victims',
'news pak sends medical search rescue teams nepal',
'china rescue team leaves for nepal sunday with members sniffer dogs and relevant medical equipment',
'heartly thanks the nepal army they are really doing well rescue providing biscuits water recovering damage done',
  'blackberrian earthquake golden temple send 1lakh delhi gurdwaras send 25000 meals those who share sardar jokes please share',
'shiromani gurudwara prabandhak commitie will send 25000 food packets from today',
'sikh bodies amristar send langar nepal earthquake victims with help indian air force',
'earthquake nepal golden temple send lac delhi gurdwaras meals daily people heart gold',
'goi and indian army prompt response nepal disaster commendable food supply being sent rescue operations underway',
'shiromani gurdwara parbandhak committee willsend 000 food packets daily nepal indiawithnepal',
'prime minister orders immediate dispatch relief medical teams',
'would like offer solar powered 500l and water filtration systems can use for nepal help wwwreaals  gmail com',
'good please volunteers medical team will leaving for nepal within week contac',
'mobilising send vital supplies including hygiene supplies water buckets shelter kits help now',
'deeply shocked over the loss lives and property the massive earthquake that hit nepal govt airlifting 2000 food pac',
'trucks relief will sent for with food water and medicine from india',
'angel nepal golden temple send lakh meals delhi gurudwaras send 25k meals daily sikhism',
'over 260 israeli aid workers full field hospital are route reports',
'delhi sikh gurdwara managemnt committee send 25k sgpc send 20k food pks everyday',
'can anyone know pick the 2000 second hand tents from sunauli and distribute the people need nepal',
'india sends member medical team nepal aid survivors',
'breaking israel send search and rescue mission nepal that will include medical teams',
'india china singapore bangladesh silanka pakistan israel turkey sending are sending immediate aid nepal',
'delhi gurudwara have informed that they are sending 000 packed food daily nepal hope this goes the people who',
'israel sends emergency aid nepal after magnitude earthquake kills more than 900 israel dispatched http',
'delhi sikh gurudwara management committee will send 000 food packages every day nepal',
'the news 000 rss volunteers sent for rescue work nepal hope they carry their food water and toilet',
'25000 food packets will sent nepal daily delhi sikh committee',
'team telling have relief supplies shelter kits household and hygiene items for approximately',
'all gorkha regts plan send nepali gorkha jawans nepal with medical officers further assist operations adgpi',
'ani news amritsar shiromani gurdwara parbandhak committee sgpc send food relief material nepal',
'oxfam preparing provide clean water emergency food you can help donating here',
'plans assist 000 people nepal temporary shelters meals water purification latrine construction',
'canada sending disaster response teams earthquake stricken nepal',
'delhi government decided that 000 food packets and 000 water bottles being sent nepal',
'with the grace volunteers send 16000 packets food earthquake victims',
'breaking news iskcon katmandu distributes food the earthquake victims iskcon news april 25th mass',
'asked packed food dispatched nepal under guidance',
  'prasanna iaf planes with rescuers aid water have landed thank you india dear rest the world please generou',
'piyush goyal has offered send engineers equipment restore the power grids nepal sushma swaraj',
'amount supplies may used for more than days mobile hospital equipped even perform surgery',
'earthquake golden temple send lakh and delhi gurdwaras send 25000 meals those who share sardar jokes please',
'swift aid from indian govt 25000 food packets daily from gurudwaras and much more there hope for nepal',
'golden temple sending lakh 25k meals daily affected areas',
'and people with food shelter water and medical assistance',
'orders massive relief for nepal 15000 blankets and 2500 tents ready kanpur airport one c130j aircraft leaves with',
'earthquake nepal golden temple send 1lac and delhi gurdwaras send 25k meals dailythose who share sardarjokes',
'ficci joins hands with govt provide relief nepal more than 000 tents blankets baby food and medici',
'kirana shop opened whole day plz get your food supplies there',
'prerna help earthquake victims nepal golden temple send lakhs meals packet daily',
'earthquake nepal golden temple send lakh and delhi gurdwaras send 000 meals daily',
'help earthquake victims nepal golden temple send lakhs meals packet daily materials cooks',
'coca cola dean kamen donate water filtration system slingshot nepal aftermath earthquake disaster via',
'extend our support the rescue efforts post the earthquake are reducing the call charges nepal sec for',
'25000 food packets from delhi sikh gurudwara management committee sent nepal daily until they need',
'sikh groups from amritsar send 000 food packets nepal daily with motive religious conversion have love',
'delhi sikh gurdwara body send langar food for nepal earthquake hit people sikh siyasat news',
'indian railway provide 1lakh mineral water nepal',
'aamaadmiparty delhi govt send food packets drinking water nepal',
'sikh bodies send food packets for nepal quake victims delhi sikh gurdwara management committee dsgmc and shiromani',
'aap government send 000 packets food and drinking water immediate relief for the people earth quake hit nepal',
'the emergency health kits given hospitals following the can cover health needs 000',
'bhaskar took stock the situation within hours and roped best medical food and military aid',
'sukhbir badal asks dsgmc and sgpc airlift 000 food packets every day nepal',
'operation maitri full swingpm will wipe nepal tearsfood medical aid reaches nepal',
'golden temple send 100 000 and delhi gurdwaras send 000 meals daily nepal earthquake affected areas',
'india sends member medical team nepal',
'earthquake nepal golden tmp send lac and del gurdwara send meal daily those who share sardar jokes please share this',
'help help nff sending responders for rescue recovery need your donation help those affected',
'3novices delhi government send food packets drinking water nepal delhi government has decided send',
'25000 packet food 25000 water pouches will sent delhi govt earthquake hit nepal proud aap govt',
'nepalgolden temple send lac delhi gurdwaras send meals dailythose who share sardar jokes plz share this too',
'anyone need drinking water contact have some can donate',
'this india for you gurdwaras preparing 000 food packets every day for iaf fly nepal aloo puri halwa',
'seva conversion shiromani gurdwara parbandhak comm wil send 25000 food packets daily nepal',
'indian for blood requirements kathmandu contact adhikari 00977 9862005225 earthquake again',
'selfless efforts made bharat proud amritsar sikh group prepared 2000 food packets for nepal everyday',
'nepal who gives emergency health kits funds quake hit nepal',
'delhi sikh gurdwara prabandak committee send 25000 langar cooked food nepal frm tmrw langar will sent http',
'goes nepal with drinking water for nepalese christian missionaries gone with holy water convert them',
'3novices india sends rail neer water earthquake hit nepal rail neer produced the indian railway caterin',
'iskcon katmandu distributes food the earthquake victims iskcon truth',
'akut medical team preparing deploy with turkish airlines flight https',
'haryana government will send food package and blankets nepal 12301485',
'sikh gurudwara committee will send 25k food packet everyday nepal this',
'fans from chitoor had started working help victims nepal started collecting food packets and',
'lalitpur red cross ambulanceservice 977 5545666 please',
'sikh bodies send 45000 food packets langar for nepal earthquake victims',
'india sends member medical team nepal the team left for nepal air force sps  ',
'india sends tonnes food tonnes water tonnes medical supplies tonnes blankets neighbour nepal',
'sgpc already sending daily food nepal salute sikh serve humanity above relig',
'turkey sending person search rescue medical team nepal',
'earthquake nepal golden temple send 1lac delhi gurdwaras 25k meals daily those who share srdar jokes pls share this too',
'the ssb has been instructed the set camps along the border provide medical help tourists crossing india nep',
'delhi sikh gurdwara managemnt committee send 25k sgpc send 20k food packets nepal everyday sikh community',
'usa msf sending teams assist victims the including highly skilled emergency surgical teams http',
'udo contact youth for blood need blood nepal',
'help earthquake victims nepal golden temple send lakhs meals packet daily',
'relief materials equipment for assistance being loaded aircraft bound for',
'medical teams engineer task force components blankets tents other items being flown nepal for earthquake resc',
'thank you bhutan bhutan joins the nepal relief operations with member medical team upon the royal command the king',
'hospital fire brigade andblood banks eye hospital 4250691 tilganga eye hospital 4423684',
'pakistan stands with nepal times need sent special planes carrying relief goods soon kathmandu airpor',
'medical team will leaving for nepal within week please volunteer contact let',
'trucks carrying relief material for the earthquake victims sent dss',
'punjabi shikh community ktm providing free food kupandole gurudwara near bagmati bridge thank you',
'no1fan bangladesh sending medical team nepal',
'paropkar ambulance service 9774260859 lalitpur red cross ambulanceservice',
'india sending water bottles nepal government useless disaster management',
'golden temple amritsar send lakh meals everday',
'delhi sikh gurdwara management committe will send 25k food packages every day nepal kudos http',
'distributing food tudikhel relief work for nepal',
'intent medicare national hospital ambulance 4467067 nepal orthopaedic hospital 4493725',
'toi earthquake nepal golden temple send lac and delhi gurdwaras send meals daily',
'delhi sikh gurdwara management committee will send 25000 food packets daily nepal',
'delhi government send food packets drinking water nepal delhi government has decided send 000',
'gujarat ready send medical teams structural eng having experience post earthquake work',
'earthquake nepal golden temple send lac delhi gurdwaras meals daily those who share sardar jokes pls',
'delhi sikh gurdwara body send langar food for nepal earthquake hit people',
'latest update first gurkha troops from queens gurkha engineer battalion deployed nepal for humanitarian aid',
'australia       world vision flies help nepal tents medicine and hygiene packs are being flown world http',
'press ind sending medical and non medical staff aid those affected the and assess medical',
'medical team from karnataka will leave nepal early morning tomorrow 27th april from residence office jayama',
'israel will send planes evacuate israelis from and will extend all possible aid nepal',
'sikhs from delhi amritsar will send abt 50k food pkts nepal daily with airforce help',
'ankit tyagi 01 delhi government send relief material nepal and bihar preparations send drinking water food packets medic',
'modi orders immediate dispatch relief and medical teams nepal directs evacuation indian tourists pti http',
'golden temple send 100 000 and delhi gurdwaras send 000 meals daily nepal earthquake affected areas',
'canada update now sending teams nepal including highly skilled emergency surgical teams',
'earthquake nepal golden temple send 1lac and delhi gurdwaras send 25k meals dailythose who share sardarjokes',
'have relief supplies shelter kits household hygiene items for around 000 households roger hodgson save the',
'pakistan sending four 130 aircraft carrying bed hospital search and rescue teams and relief items nepal tomorrow',
'timesofindia shiromani gurdwara parbandhak committee sgpc send food relief material nepal',
'25000 packets food and 25000 pouches water dispatched aap govt nepal',
'food medicines taken milk food oxygen regenerators blankets being moved foreignsecretary',
'india sends member medicl team nepal aid survivors nadda http',
'ind are currently sending medical and non medical teams aid those affected the',
'army rushes medical aid nepal indigo spacejet taking relief materials free cost nepal',
'call for help use 1st helplines app',
'timesnow pak sends planes with relief goods field hospital several paramedics rescue workers earthquake hit nepal pti',
'assessment teams search and rescue experts and medical personnel and supplies are their way from israel kathmandu',
'for water please contact 9851035527',
'2000 rss volunteers including medical teams are the way nepal shiromani gurudwara prabandh committee',
'two c130 and two c17 aircraft will nepal today carrying rescue teams doctors field mobile hospitals sniffer',
'earthquake nepal and northern india 2015 kathmandu ambulance andemergency helpline numbers',
'usa msf sending teams assist victims the including highly skilled emergency surgical teams http',
'blood required than please contact representative nepal voluntary blood donor society',
'national disaster helpline number 1078 made operational people can dial using std code 011 011 1078',
'latest delhi govt send food packets drinking water nepal zee news ndtvdelhi govt',
'adgpi medical teams being deployed nepal including teams which have already reached',
'undr the holy guidance saint gurmeet ram rahim singh insan 16000 food packets sent nepal',
'breaking ind army c130 taken off nepal with foods water ndrf team doctors nurse  ',
'send 2000 volunteers with medical team',
'health ministry has rushed tonnes medicines nepal today the ministry has also sent member medical',
'daily lakh water bottle send nepal from india',
'ndrf team from india dogs tonnes equipment handed over nepal army for rescue ops indian embassy ktm',
'india big effort for relief rescue nepal planes load stuff medicines water blankets tents food ten choppers ndrf teams',
'bloodbanks kantipur hospital newbaneshwor 4498757 hospital and research centre 4476225',
'toi sikh bodies send food packets for nepal quake victims delhi sikh gurdwara management committee dsgmc',
'india sending uavs map the destruction caused the earthquake nepal',
'small but not small enough not able help our neighbour his majesty sends member team with medical',
'opening warehouses with relief items for refugees making available all available stocks for',
'the says has enough blood rejects any and tells stand',
'israel sending aid teams nepal after quake israel was sending delegation nepal saturday',
'leaving friday nepal with the hospital medical team',
'bhutan joins the nepal relief operations with member medical team surgeons nurses and technicians upon the roya',
'india doing its best save people from nepal',
'golden temple send lac delhi gurdwaras send 25k packets meal daily nepal thanx',
'earthquake nepal golden temple send lac delhi gurdwaras send meals daily those who share sardar jokes share this',
'spoke cmo asked them everyone that medical treatment will free cost for injured ahluwalia siliguri',
'sacha sauda sent 16000 sets food for earthquake victimsproud son msg',
'haryana govt airlift 000 food packets tomorrow nepal',
'rajasthan announces 000 relief kits including food packets plastic sheets medicines water bottles blankets',
'canada currently sending medical non medical teams nepal aid those affected the',
'thank you minister piyush goyal has offered send engineers equipment restore the power grids nepal sush',
'unicef delivering prepositioned supplies meet children immediate needs for protection water sanitation',
'thinking nepal all those affected this tragic earthquake sending medical teams support them',
'haryana offers food packets blankets for quake hit nepal outlook wires',
'will sending relief material medical help more info awaited',
'india sends rail neer water quake hit nepal',
'who handed over emergency health kits meds med supplies usd 175k the min health',
'ind india sending medical and non medical staff aid those affected the and assess medical',
'lakh bottles rail neer water will reach nepal',
'nepal earthquake india and china send rescue teams himalayan nation',
'kailash bakery providing free food the earthquake victims kailashbakery  gmail com',
'relief materials equipment earthquake assistance being loaded aircraft bound kathmandu',
'medical teams being deployed nepal including teams which have already reached',
'for food and blood 4412430 4412253 0 with hashtags reach people',
'air force too will fly doctors paramedics medicines equipment',
'nepal earthquake relief surgical material medicines sachin sharma gopal hospital aam aadmi party ghaziabad http',
'excellent decision all gorkha regiments indian army send nepali gorkha jawans nepal with medical officers ass',
'nepal quake dsgmc sgpc send 000 food packets every day kathmandu the economic times',
'india sends member medical team quake struck nepal',
'delhi sikh gurudwara management will send 000 food packets daily',
'south korea sending person disaster response team help with the aftermath the earthquake fore',
'food alrdy been dispatched nepal although demand',
'also the aircrafts carrying mobile hospitals packed meals water ground rescue forces have reached nepal',
'ready send medical team and survival kits pls donate our disaster fund',
'govt news conference ton blankets ton water ton food material has been sent',
'share this for blood requirements kathmandu nepal contact adhikari 00977 9862005225',
'temple send lakh and gurudwaras send 25 meals daily hats off http',
'the ministry has also sent member medical team the earthquake affected areas nepal provide emergency medical relief',
'tyagi 01 delhi government send relief material nepal and bihar preparations send drinking water food packets medic',
'sikh bodies send 25k and 20k food packets everyday for nepal quake victims via',
'lunger sent nepal for earthquake victims akali dal badal through indian air force air craft today 3000 packets',
'goi has sent lac water bottles nepal',
'india sends rail neer water quake hit nepal',
'tonnes water sent via',
'great kudos bjp rushed tonnes medicines member team doctors and medical experts quake hit areas nepal',
'nepal earthquake what india doing help india sending disaster response teams medical aid and food',
'gandhi along with the team doctors and volunteers offer services for relief work nepal earthquake tragedy http',
'are sending emergency shelter team nepal support response the earthquake thank you',
'tonne relief materials carrying food medicinesearth excavation equipments have been sent nepal from india http',
'are collecting medicines tents water bottles biscuit packets for nepal are sending all matterial with',
'israel sending aid team nepal after quake',
'bihar govt sending buses from muzaffarpur today evacuate earthquake victims pokhra nepal will brought raxaul from pokhra',
'help for gorkha earthquake victims are collecting foods warm clothes blankets and mineral waters',
'ambulance and police emergency helpline numbers nepal',
'nepal earthquake relief surgical material medicinesfrom sachin sharmamedical director gopal',
'are working with ministry health send our doctors and paramedical staff nepal',
'uday foundation adhchini delhi collection point send medical supplies for quake hit nepal info',
'medical treatment chabel operating the road',
'timesnow all gorkha regts plan send nepali gorkha jawans nepal with medical officers further assist operations adgpi',
'ndrf teams have been sent bihar and ndrf team operation rajnath singh http',
'india sends member medical team nepal press trust indiathnxx',
'for blood requirements kathmanducontact adhikari 00977 9862005225',
'earthquake nepal golden temple send 1lacdelhi gurdwaras send meals daily those who share sardar jokes plz',
'sends trucks mineral water biscuits and medicines affected',
'india showing the true brotherhood with nepal helping the victims earthquake sending all facilities doctors rescue teams',
'per the requirements raised pmo first lot 16000 packed food has been sent nepal the mrng under',
'emergency operating room operational nepal medical college being reserved for pregnant and severely needed ones',
'tonnes equipment ndrf teams teams doctors bsnl calls nepal local rates railways support funds donation',
'has offered send engineers and equipment restore the power grids nepal are extending what ever',
'sikh groups from amritsar delhi voluntarily send 000 food packets nepal daily with motive',
'israel preparing send search and rescue teams along with humanitarian aid nepal after over',
'brilliant gesture and planning 1lac neer water bottles will sent nepal ind rail',
'redcross has sent 000 sets tents for quake victims evening drizzle adds victims woes',
'pakistan sends dry food medical search and rescue teams nepal',
'gujarat govt send 000 food packets nepal',
'doval ready nepal provide medical aid one call distance move nepal',
'trama center and health worker and volunteers doing amazing job quick',
'handed over 4emergency health kits meds med supplies usd 175k the min health',
'team orthopedic neurosurgeon general medicine anesthetic ready dispatched nepal waiting for ndrf call',
'mission depart 2230 this evening 260 strong medical search rescue full field hospital http',
'nepal golden temple send lac delhi gurdwaras snd meals daily those who share sardar jokes kindly share this',
'india sending buses rescue and evacuate stranded people nepal medical teams will also deployed along border',
'spread colleague has offered send engineers and equipment restore the power gri',
'earthquake nepal golden temple send lakh and delhigurdwaras send 25000 meals daily those who share sardar jokes please',
'update our medical team still there for the annual medical camp',
'planning send some food clothes some money for victims earthquake victims from dodhara chandani',
'yggnrd nepal helping earthquake displayed people erecting tents providing drinking water   nepal',
'drinking water plus emergency relief supplies headed aircraft photo',
'sikh bodies send langar for nepal earthquake victims the times india 50k food pkt',
'one earthquake nepal golden temple send lakh meals and delhi gurdwaras send 25000 meals daily those http',
'sgpc send 100 000 parshade with 000 food packets nepal immediately',
'delhi sikh gurudwara managemnt committee snd 25k smcs snd 20k food packets nepal evryday',
'indian govt prompt response disaster nepal makes feel proud low call rates doctors medicine food water',
'international aid groups are coming nepal rescue',
'arizona doctors with group medical mission nepal caught earthquake zone',
'israel sending aid teams nepal after quake israel was sending delegation nepal sps  ',
'bloodbanks hospital and research centre 4476225 norvic hospital 4258554',
'shiromani gurdwara parbandhak committee sgpc send food relief material nepal reports',
'meaindia earlier today relief materials and equipment for earthquake assistance being loaded aircraft bound for kathmandu',
'delhi sikh gurudwara committee send 25000 food packets nepal everyday',
'oxfam ready respond with lifesaving essentials clean water sanitation emergency food supplies',
'gain followers bishal bazaar ambulance service 977 4244121 red cross ambulance service 9774228094',
'rescue medical teams health damage assessment teams sought nepal jaishankar fgn secy teams being dispatched',
'india earthquake ten karnataka doctors leave for nepal from bengaluru',
'provide relief victims nepal 130 acs with bedded hosp army drs special searchrescue teams food item',
'earthquake nepal indian army takes major rescue and relief oepration',
'earthquake nepal golden temple send lac and delhi gurdwaras snd meals daily dos who share sardar jokes please share this too',
'best example send 100 000 food packets hit',
'rss send swayamsevak nepal help victims seculars could not digest need hajmola',
'true gurmeet ram rahim singh insan sent 16000 food packets nepal for victims http',
'you need shelter please contact 9841777536 location manbhawan jawalakhel',
'rss have sent 2000 swyamsevak nepal shiromoni gurudwara sent 25000 food packets nepal salute',
'india sending uavs map the destruction caused the earthquake nepal',
'earthquake nepal golden temple send lac and delhi gurdwaras send meals daily those who share http',
'relief centres established for maldivians nepal various locations maldives hon consul nepal food water medical team standby',
'gujarat govt send 000 food packets nepal gujarat government cooperation with citize gujarat times',
'team doctors leaving for nepal from king george medical college via gorakhpur samajwadi party',
'delhi govt sending 000 packets food and 000 pouches drinking water immediate relief today',
'great job shiromani gurdwara parbandhak committee will send 000 food packets daily nepal',
'earlier today relief materials and equipment for earthquake assistance being loaded aircraft bound for',
'helpline numbers nepal bishal bazaar ambulance service 977 4244121 red cross ambulance servi',
'has offered send engineers and equipment restore the power grids nepal this will great help for',
'earthquake emergency numbers vired cross ambulance service nepal 00977 422 8094',
'live india steps rescue ops send military aircraft kathmandu nepal toll crosses 2300',
'nepal earthquake medical team sent nepal from himachal union health and family welfare minister nadda',
'latest update from ocha international medical teams route nepal',
'gandhi india sending uavs map destruction',
'help victims earthquake nepal golden temple send lac and delhi gurdwaras send 25000 meals',
'preparing for relief camp for nepal earthquake victims akali dal badal',
'tarang have support group running the end airport have food water painkillers come you',
'two israeli flights assigned nepal for rescue and medical aid',
'delegation that flew out incl 240 medical logistics officers field hospital crew',
'vital aid will given those affected the nepal earthquake islamic relief staff have already been deployed http',
'bjpdelhistate piyushgoyal has offered send engineers and equipment restore the power grids nepal are extending what ever help',
'donating blood running food camp for people nepal',
'people viber billing switched off use viber communicate wherever internet connection available',
'delhi shiromani gurudwara prabandhak commitie will send 25000 food packets day frm today nepal',
'delhi government send food packets drinking water nepal delhi government has sps  ',
'new age south african medical search and rescue personnel prepare nepal',
'team technical experts flying from the with supplies provide clean water sanitation and emergency food',
'sgpc dsgmc will tomorrow send 000 000 food packets for earthquake victims nepal',
'delhi bjp sent truck rice medicine relief material shiromani gurdwara parbandhak committee will send 25k food packe',
'golden temple send 100 000 delhi gurdwara will sending 000 meals daily for nepal earthquake victims thank ever',
'modi govt sent ton relief material team doctors ndrf jcbs food water medicines nepal',
'chalise outbound viber out calls from nepal are currently free free inbound viber out calls nepal will',
'indian railway has desptchd one lakh minerl water bottls relief material through the iaf',
'plz much ambulance and police emergency helpline numbers nepal congress http',
'got touch with general anurag who will help sending medical aid across nepal',
'demand for safe high quake hit india sends 000 bottles packaged water',
'help earthquake victims nepal golden temple send lakh meals packets daily',
'pak sends planes with relief goods field hospital several paramedics rescue workers earthquake hit nepal pti',
'pakistan sending medical and rescue teams nepal via',
'dera sacha sauda dispatched 16000 food packages for nepal requested pmo',
'idf search and rescue team field hospital depart for nepal tonight total 260 personnel and equipment http',
'shelterbox sending team assess the need for shelter following the powerful earthquake this morning http',
'vasundhara raje announces 000 relief kits including food packets plastic sheets medicines water bottles blankets sent nepal',
'india sends mobile hospital with doctors medical aid hospitals nepal don have enough rooms doctors help',
'organising transport for docs medical staff volunteer contact vidyakrishnan 13  gmail com',
'charcha meaindia earlier today relief materials and equipment for earthquake assistance being loaded aircraft boun',
'its true staint sent 16000 food packets nepal for victims',
'paropkar ambulance service 9774260859 lalitpur red cross ambulanceservice',
'update nepal earthquake 18 medical teams being deployed nepal including teams which have already reached',
'the says has enough blood rejects any and tells stand',
'2000 ready eat meals among other food items water medicines 200 tents 600 blankets other necessities sent nep',
'indian offers units tents units family packs etc earthquake victims nepal picture still',
'our brothers are sending materials like help humans and not like there for conversion',
'needs help help children families nepal sending medical etc teams http',
'govt send relief material trucks quake hit nepal comprising trucks mineral water trucks biscuits and truck medicines',
'adgpi all gorkha regts planning send nepali gorkha jawans nepal with medical officers further assist the operations',
'anyone struggling find food thamel jamsikhel lazimpat tings tea kitchen open trying their best https',
'israel set send emergency aid nepal after quake kills over 200 the times israel',
'respect colleague has offered send engineers and equipment restore the power grids nepal',
'mubasher are distributing quality lights people fund lights via',
'canada sending medical logistical teams 000 kits relief items medical supplies',
  'inqlb earthquake nepal golden temple send 1lac delhi gurdwaras 25k meals daily those who share srdar jokes pls',
'colleague has offered send engineers and equipment restore the power grids nep',
'trucks carrying relief material for the earthquake victims sent dss',
'earthquake over 2600dead nepal indiaindia sends 13military aircrafts 700ndrf personnel for relief work 1935 indians evacuated',
'csr from the victims earthquake ktm valley can contact for needs thanks',
'nepal has requested for drinking water has decided send lak liter rail neer over night',
'delhi govt send 25k food packets 25k bottles drinking water nepal immediately talks assures more help thx',
'dispatches four 130 planes carrying bed field hospital medical teams relief supplies',
'india sends rail neer water earthquake hit nepal indian railways which produces its own packaged drinki',
'apart from india help pakistan will also send aircraft with facility bed hospital nepal good',
'bihar extends help nepal with food medicines victims outlook wires',
'nepal earthquake modi called meeting plane with relief material food waterbottles landed 6pm',
'tahir delhi govt send 000 packets food and drinking water immediate relief for the people earth quake hit nepal',
'nepal earthquake aid material doctors and relief workers from near countries began arriving',
'delhi sikh gurdwara body send langar food for nepal earthquake hit people',
'hindu humanitarian group iskcon nepal sets medical camps rescue teams food for life for',
'delhi govt send relief material nepal send drinking water food packets medicines  ',
'sikh bodies send food packets for nepal quake victims',
'requester pmo india 1st lot food dispatched 26th april nepal',
'golden temple amritsar send lakh meals everday',
'earthquake nepal golden temple send lac and delhi gurdwaras send thousand meals daily those who',
'army dispatch 130 carryng bed hospital special search rescue teams relief items',
'govt send 000 food packets',
'setup field hospital tomorrow morning provide medical facilities',
'india sends rail neer water earthquake hit nepal new delhi indian railways which produces its own',
'pak sends planes with relief goods and several paramedics rescue workers earthquake hit pti',
'chintan indian medical team members',
'around 150 tonnes equipment flown kathmandu tonight india launches relief ops quake hit nepal',
'divya 1st lot 16000 food packets has already been dispatched nepal',
'pakistan army sending 2000 meals 200 tents medicine 600 blankets other necessary items htt',
'blood needed around ilam ready just mention',
'earthquake nepal golden temple send 1lac delhi gurdwaras meals daily those who share sardar jokes pls share this too',
'first iaf aircraft leaves hindon airbase with relief equipment for nepal',
'salman golden temple will send lakh food packages daily aid victims',
'set send emergency aid after quake kills 200 plus the times israel',
'churches will also send food packets nepal but after convert christianity offcourse',
'golden temple send lac and delhi gurdwaras send meals daily those who share sardar jokes note this',
'blood banks hospital and research centre 4476225 norvic hospital 4258554',
'sends member medical team fresh tremor jolts live',
'mayavaram delhi govt has decided send 000 packets food 000 pouches drinking water relief for the people ear',
'blogfeeds israel prepares send emergency aid nepal after massive quake 200 israelis area yet',
'chinese medical team stationed will join earthquake rescue and relief work',
'sending teams 3000 kits non food items and medical kits those affected the',
'2nd rapid aero medical team aerial mobile hospital will depart from hindon air base for kathmandu',
'india doing commendable job nepal sending dmrf and field ambulance units for assisting the effected people',
'sgpc will send 100 000 food packets victims',
'israel sends humanitarian aid nepal the hours following the earthquake israeli magen david adom conducted',
'india sends aircrafts nepal today including tonnes supplies mobile hospital ndrf teams',
'control room ministry external affairs helpline numbers',
'india send rescue personnel and medicine earthquake hit nepal',
'bharat sevashram sangha started relief work earthquake hit nepal cooked food being distributed the outskirts kathmandu',
'fly emergency medical help food struck http',
'earthquake nepal golden temple send lac and delhi gurdwaras send meals daily those who share sardar jokes pls share this too',
'india the job ndrf personnel crack medical team with relief rushed',
'india sends rail neer water earthquake hit nepal indian railways which produces sps  ',
'indian railway send one lakh water bottle nepal will reach today night bsnl and mtnl take only national charges from ind nep',
'timesnow piyush goyal has offered send engineers equipment restore the power grids nepal sushma swaraj',
'sending langar twice day over one lakh earthquake victims nepal',
'yes our ngo pushed one force ambulance action yesterday crossed guj raj border today will reach nepal 1st may',
'sends medical search and rescue teams',
'pakistan air force flying 130s nepal earthquake affected areas carrying hospital doctors sniffer dogs tent',
'israel preparing send search rescue teams along with humanitarian aid',
'sikh bodies send 25000 food packets for nepal earthquake victims',
'kudos dealhigovt delhi send food packets drinking water nepal the economic times',
'varanasi will sending relief material medical help more info awaited',
'earthquake nepal golden temple send lac and delhi gurdwaras send meals daily those who share sardar jok',
'welcome step send food packets drinking water nepal',
'pakistan sends medical search and rescue teams nepalread more',
'strong chinese governmentmedical team arrived nepal earthquake',
'pakistan army paf did great job very short time sending medicine blankets tents bed hospital doctors nepal',
'1st lot 16000 food packets sent nepal the call undr guidance',
'exclusive news sikh bodies send food packets for nepal quake victims has been published',
'railways send lakh litre water nepal more todaycoordinationbureaucrats working with devotion involvemente',
'our medical team want help quake victims nepal wth relief medicines pls help with transport',
'always msg helping victims 16000 food packets medical help send nepal tomorrow',
'sikh bodies send around 45k food packets daily nepal delhi sikh gurdwara management committee dsgmc and',
'iaf 130 hercules stand team doctors ndrf jcbs food water medicines being put together send nepal',
'body sends 000 packets',
'paf aircraft rescue relief assistance incl bed mobile hospital have left for http',
'guruka dera sacha sauda mobilized 16000 food packages nepal',
'next iaf plane leave for nepal mins this relief going blistering speed 15000 blankets 2500 tents ready',
  'wsjindia what india doing help nepal sending disaster response teams medical aid and food supplies',
'blood banks patan hospital 5522278 5522266 bhaktapur hospital 6610676 mental hospital 5521333',
'indian army has deployed medical teams earmarked medical teams have reached deployed while the rest are stan',
'hospital fire brigade and blood banks telephone number nepal eye bank 4493684',
'unhcr rushes plastic sheeting and solar powered lamps nepal earthquake survivors',
'truck relief material send earthquake victims sirsa via',
'are sending teams assist those affected the including skilled emergency surgical teamshttp',
'instructed set camps along the border provide medical help tourists crossing nepal border',
'nepal centre providing shelter 100 ppl volunteers providing food water',
'helpline ambulance and police emergency helpline numbers nepal country code 0977 nametelephone numbers',
'intent kathmandu medical college 4476152 nepal medical college teaching hospital jorpati 4486008',
'bhatt railway min sending water via trains job supervising overall ops yes indian govt working for',
'delhi govt send food packets drinking water nepal zee news ndtvdelhi govt send food packets drin',
'bangladesh govt declared stand beside nepal with rescue team medical and other supports http',
'various sikh bodies india send packets food abt 25k per day relief nepal',
'cnn reporting pakistani medical teams have arrived nepal assist local authorities india has sent relief goods',
'please paropkar ambulance service 9774260859',
'best example send 100 000 food packets hit',
  'hospital fire brigade and blood banksnametelephone numbersnepal eye bank 4493684 nepal eye',
'aap govt send 000 packets food and drinking water immediate relief for the people earth quake hit nepal',
'food also being cooked her and sent for the people nepal during this crisis media will not show this http',
'16k food packets delivered rescue operation  ',
'govt dispatches trucks relief material doctor delegation from king george medical university for nepal',
'usa also sending 000 kits non food items and medical kits those affected the',
'basit pakistan sends medical and food supplies nepal',
'qatar india dispatched military aircraft nepal loaded with tonnes food blankets and other aid stepping relief',
'distributing food settling all centres turned into centres',
'the turkish red crescent initially sent 000 blankets and hundreds food packages the earthquake region',
'retweet blood bank and food bir hospital 4223807 4221988',
'are sending medical and non medical teams well 3000 kits non food items and medical kits nepal from',
'nepal earthquake golden temple send lac delhi gurdwaras send meals daily those who share sardar jokes please share this too',
'sometimes beauracracy political management needs credited too lac water thru railways the way nepal',
'swift relief material reach call nepal charged local call 250 indians airlifted khatmandu medical team way govt tht works',
'israel prepared assist searching for the missing medical care the injured',
'his majesty commanded surgeons medical specialists nurses technicians join the medical relief ope',
'delhi sikh gurudwara comitee send 25000 food packets daily nepal',
'dera sacha sauda send 16000 chapatis with pickles for persons who suffered earthquake http',
'providing wai noodkes other foods and services disaster victims',
'nepal sri lanka sends medical teams rescue units nepal',
'redcross ambulance service 4228094',
'great news 16000 food packets sent nepal today morning many more queue',
'ambulance and police emergency helpline numbers nepal   screen shot attached who faced difficulty open from url http',
'mobile hospital with orthopaedic doctors are coming nepal from india planning work hrs 150 tons',
'earthquake temple send lac and delhi gurdwaras send 25k meals daily those who share sardar jokes please share this too',
'thanku for 200retweets still please retweet copy paste with hashtag lalitpurredcross ambulance service 5545666',
  'razeen srilankan airforce team with medical aids off',
'loco our glorious indian railways provides helping hand nepal lakh rail neer water bottles sent',
'000 rss personnel with much needed medical supplies and other help the first reach earthquake damaged zones',
'com iskcon nepal sets medical camps rescue teams and food for life assist earthquake victims',
'israel prepares send emergency aid nepal after massive quake',
'finally fans started help victims sending 000 blankets nepal great job the fans',
'ddnewslive tones medical supplies sent indian medical team deployed',
'constant touch wid govts bihar bengal under control need for panic ndrf teams being mobilised for nepal',
'earthquake golden temple send lakh and delhi gurdwaras send 25000 meals those who share sardar jokes please',
'air force fly doctors paramedics medicines equipment http',
'just electricity available shankhamul area people are staying outside',
'bhartij narendra modi calls meeting review situation arising out quake indian relief teams and equipment sent',
'blankets are their way nepal from victoria stay strong nepal are with you victorians stand together for nepal',
'sikh bodies amristar send langar nepal earthquake victims with help indian air force',
'yalla set send emergency aid after kills 200 plus',
'sgpc will sending food packets for the earthquake victims nepal approximately 25000 food packets sent dail',
'insan per the requirements raised pmo first lot 16000 packed food has been sent nepal under the morning',
'sukhbir badal sends off first lot langar earthquake victims nepal ctags',
'centre nepal providing food relief and shelter organising blood donation',
'nepal earthquake india and china send rescue teams himalayan nation',
'free 24hr medicine service prasit kandel 9779851133 822 shailesh sharma 9779851017 553',
'yogi adityanath affected can take shelter gorakshnath temple accommodation food medical help gorakhsnath hospital',
'earthquake ndrf teams sent bihar and ndrf team operation says rajnath singh',
'doctors say there enough manpower but less beds opds and medicines the hospital',
'25000 food packets daily being send nepal but one covered the news',
'pgvs and christian aid relief team gorkha district nepal arrived with hours earthquake and provided wash and first aid',
'india sends member medical team nepal health minister nadda personally sps  ',
'blood donation drive tomorrow alsosiliguri come forward and help nepal donation camp',
'team doctors and volunteers its way nepal get touch with you should need more assistance',
'dsgmc send 000 food packets daily nepal for relief efforts united sikhs and khalsa aid groups head htt',
'youth airlifted 000 food packets nepal today guruji saint has given call https',
'shiromani gurdwara parbandhak committee will send 000 food packets daily nepal',
'sgpc will sending food packets for the earthquake victims nepal approximately 25000 food packets sent dail',
'rajasthan announces 1000 relief kits with food packets plastic sheets medicines water bottles blankets sent',
'medical teams being deployed incl teams which have already reached',
'international aid groups rush reach nepal earthquake victims the ifcr said was extremely concerned abou',
'golden temple send 100 000 delhi gurdwara will sending 000 meals daily for nepal earthquake victims thank ever',
'please share with othershospital and emergency contacts nepal',
'china sending   million worth emergency shelters clothing blankets and power generators nepal',
'nea supplying electricity',
'planes leave for tmrw carry meds med team bed hospital search rescue experts dry food tents blankets',
'sikh bodies send food packets for nepal quake victims delhi sikh gurdwara management committe',
'000 rss people have gone aid efforts nepal',
'israel sending aid and rescue team quake stricken nepal which will land nearest airport',
'indian teams land nepal help with quake relief india sending disaster response teams medical aid and',]
for i in s:
    tweet_clean(i)
